import * as fs from "fs";
import * as path from "path";
import { SkillRecord } from "./types";

const HEADER = "<!-- generated by kiro-skills-loader. do not edit by hand. -->";

/**
 * Compute the steering filename for a skill. We use a stable, namespaced name
 * so we never collide with hand-written steering files.
 */
export function steeringFileName(skill: SkillRecord): string {
  const cat = skill.category.join("-").toLowerCase() || "uncategorized";
  return `skill--${cat}--${skill.id}.md`;
}

export interface SteeringOptions {
  inclusion: "fileMatch" | "manual" | "always";
  maxChars: number;
}

/**
 * Render the steering file body.
 *  - inclusion=fileMatch: front-matter with auto-derived patterns
 *  - inclusion=manual:    user must type #<file>
 *  - inclusion=always:    no front-matter (default Kiro behavior is always-on)
 */
export function renderSteering(skill: SkillRecord, opts: SteeringOptions): string {
  const lines: string[] = [];

  if (opts.inclusion === "fileMatch") {
    const patterns = derivePatterns(skill);
    lines.push("---");
    lines.push("inclusion: fileMatch");
    lines.push(`fileMatchPattern: '${patterns.join(",")}'`);
    lines.push("---");
    lines.push("");
  } else if (opts.inclusion === "manual") {
    lines.push("---");
    lines.push("inclusion: manual");
    lines.push("---");
    lines.push("");
  }

  lines.push(HEADER);
  lines.push("");
  lines.push(`# Skill: ${skill.frontmatter.name ?? skill.id}`);
  lines.push("");
  if (skill.frontmatter.description) {
    lines.push(`> ${skill.frontmatter.description}`);
    lines.push("");
  }
  lines.push(`Source: \`${path.relative(process.cwd(), skill.skillPath).replace(/\\/g, "/")}\``);
  lines.push(`Category: ${skill.category.join(" / ") || "(root)"}`);
  if (Array.isArray(skill.frontmatter.keywords) && skill.frontmatter.keywords.length) {
    lines.push(`Keywords: ${(skill.frontmatter.keywords as string[]).join(", ")}`);
  }
  lines.push("");

  // Embed body, truncated to maxChars
  const body = skill.body.length > opts.maxChars
    ? skill.body.slice(0, opts.maxChars) + "\n\n... (truncated, see source SKILL.md)"
    : skill.body;
  lines.push(body);
  lines.push("");

  // List companion files so the agent can pull them in if needed
  if (skill.companions.length) {
    lines.push("## Companion files");
    lines.push("");
    const grouped = new Map<string, string[]>();
    for (const c of skill.companions) {
      const key = c.category || "(loose)";
      if (!grouped.has(key)) grouped.set(key, []);
      grouped.get(key)!.push(c.relPath.replace(/\\/g, "/"));
    }
    for (const [cat, files] of grouped) {
      lines.push(`- **${cat}**`);
      for (const f of files) {
        lines.push(`  - \`${f}\``);
      }
    }
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Heuristic file patterns based on category and id. Covers common cases
 * (languages, frameworks). Always includes "*" as a fallback.
 */
function derivePatterns(skill: SkillRecord): string[] {
  const patterns = new Set<string>();
  const cat = skill.category.map(c => c.toUpperCase());
  const top = cat[0] || "";
  const sub = cat[1] || "";

  const langExt: Record<string, string[]> = {
    PYTHON: ["py", "ipynb"],
    JAVASCRIPT: ["js", "mjs", "cjs"],
    TYPESCRIPT: ["ts", "tsx"],
    JAVA: ["java"],
    KOTLIN: ["kt", "kts"],
    RUST: ["rs"],
    GO: ["go"],
    CSHARP: ["cs", "csproj", "sln"],
    CPP: ["cpp", "cc", "cxx", "h", "hpp"],
    RUBY: ["rb"],
    PHP: ["php"],
    SWIFT: ["swift"],
    ELIXIR: ["ex", "exs"],
    HASKELL: ["hs"],
    SCALA: ["scala", "sbt"],
    JULIA: ["jl"],
    LUA: ["lua"],
    BASH: ["sh", "bash", "zsh", "ps1"]
  };

  if (top === "LANGUAGES" && langExt[sub]) {
    for (const ext of langExt[sub]) patterns.add(`**/*.${ext}`);
  } else if (top === "WEB") {
    patterns.add("**/*.html");
    patterns.add("**/*.css");
    patterns.add("**/*.js");
    patterns.add("**/*.ts");
  } else if (top === "DATABASE") {
    patterns.add("**/*.sql");
  } else if (top === "MOBILE" && sub === "MAUI") {
    patterns.add("**/*.cs");
    patterns.add("**/*.xaml");
  }

  // Match files referencing the skill name itself (rough but useful)
  patterns.add(`**/${skill.id.replace(/^\d+-/, "")}*`);
  patterns.add("README*");
  return [...patterns];
}

/**
 * Write the steering file for a skill, creating .kiro/steering if needed.
 * Returns the absolute path written.
 */
export function writeSteering(workspaceRoot: string, skill: SkillRecord, opts: SteeringOptions): string {
  const dir = path.join(workspaceRoot, ".kiro", "steering");
  fs.mkdirSync(dir, { recursive: true });
  const filePath = path.join(dir, steeringFileName(skill));
  const content = renderSteering(skill, opts);
  fs.writeFileSync(filePath, content, "utf8");
  return filePath;
}

/** Remove a previously generated steering file for a skill. Safe if missing. */
export function removeSteering(workspaceRoot: string, skill: SkillRecord): boolean {
  const filePath = path.join(workspaceRoot, ".kiro", "steering", steeringFileName(skill));
  if (fs.existsSync(filePath)) {
    fs.unlinkSync(filePath);
    return true;
  }
  return false;
}

/** Remove every generated skill steering file. Used before a full regen. */
export function purgeGeneratedSteering(workspaceRoot: string): number {
  const dir = path.join(workspaceRoot, ".kiro", "steering");
  if (!fs.existsSync(dir)) return 0;
  let count = 0;
  for (const name of fs.readdirSync(dir)) {
    if (name.startsWith("skill--") && name.endsWith(".md")) {
      try {
        fs.unlinkSync(path.join(dir, name));
        count++;
      } catch { /* ignore */ }
    }
  }
  return count;
}
